version: '3'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server
    ports:
      - '6379:6379'

  redisinsight:  
    image: redislabs/redisinsight
    container_name: redis-redisinsight
    ports:
      - '8001:8001'